CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  avatar_url TEXT
);

CREATE TABLE IF NOT EXISTS stories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER FOREIGN KEY REFERENCES users(user_id),
  title TEXT,
  content TEXT,
  last_modified TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS published_stories (
  story_id INTEGER FOREIGN KEY REFERENCES stories (id) PRIMARY KEY,
  published_at TIMESTAMP NOT NULL,
  cover_image_id INTEGER FOREIGN KEY REFERENCES images (image_id)
);

CREATE TABLE IF NOT EXISTS images (
  image_id INTEGER PRIMARY KEY AUTOINCREMENT,
  image_path TEXT
);

CREATE TABLE IF NOT EXISTS claps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  story_id INTEGER INTEGER FOREIGN KEY REFERENCES stories (id) NOT NULL,
  clapped_by INTEGER FOREIGN KEY REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  comment_on INTEGER FOREIGN KEY REFERENCES stories (id) NOT NULL,
  comment_by INTEGER FOREIGN KEY REFERENCES users (user_id),
  commented_at TIMESTAMP NOT NULL,
  comment TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS followers (
  user_id INTEGER FOREIGN KEY REFERENCES users (user_id),
  follower_id INTEGER FOREIGN KEY REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS tags (
  story_id INTEGER INTEGER FOREIGN KEY REFERENCES stories (id) NOT NULL,
  tag TEXT NOT NULL
);
