CREATE TABLE IF NOT EXISTS users (
  username VARCHAR(50) UNIQUE NOT NULL,
  avatar_url TEXT
);

CREATE TABLE IF NOT EXISTS stories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author VARCHAR(50) UNIQUE NOT NULL,
  title TEXT,
  content TEXT,
  last_modified TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS published_stories (
  story_id INTEGER PRIMARY KEY,
  published_at TIMESTAMP NOT NULL,
  cover_image_id INTEGER 
);

CREATE TABLE IF NOT EXISTS images (
  image_id INTEGER PRIMARY KEY AUTOINCREMENT,
  image_path TEXT
);

CREATE TABLE IF NOT EXISTS claps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  story_id INTEGER NOT NULL,
  clapped_by INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  comment_on INTEGER NOT NULL,
  comment_by INTEGER NOT NULL,
  commented_at TIMESTAMP NOT NULL,
  comment TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS followers (
  user_id VARCHAR(50) UNIQUE NOT NULL,
  follower_id VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
  story_id INTEGER NOT NULL,
  tag TEXT NOT NULL
);
